### ISSUE TITLE
[Bugreport] Error during migration

### ISSUE THREAD

**Issue by Ceddix** [dklima/coreprotect_db_migration#3]
Hi 👋🏻 

So I've tried migrating a `database.db` file, that CoreProtect generated by accident to a database and at the beginning it seemed to work perfectly. The file is very big, so I had to wait a bit, but suddenly, at the `co_signs` database (+-2 hours waited), an error occurred and the script aborted. I restarted everything but the same error occurred. Is there anything you can do? It's very important for me at the moment.

```
Truncating co_sign... done
Migrating co_sign with 18324 records... /usr/lib/ruby/vendor_ruby/mysql2/error.rb:55: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/vendor_ruby/mysql2/error.rb:94: warning: Using the last argument as keyword parameters is deprecated
Traceback (most recent call last):
        8: from ./migration.rb:89:in `<main>'
        7: from ./migration.rb:89:in `each'
        6: from ./migration.rb:106:in `block in <main>'
        5: from ./migration.rb:70:in `my_prepare_to_insert'
        4: from ./migration.rb:34:in `my_insert_data'
        3: from /usr/lib/ruby/vendor_ruby/mysql2/client.rb:130:in `query'
        2: from /usr/lib/ruby/vendor_ruby/mysql2/client.rb:130:in `handle_interrupt'
        1: from /usr/lib/ruby/vendor_ruby/mysql2/client.rb:131:in `block in query'
/usr/lib/ruby/vendor_ruby/mysql2/client.rb:131:in `_query': Unknown column 'data' in 'field list' (Mysql2::Error)
```

Hopefully you can help me relatively quickly. Thank you in advance!
Greetings, Ceddix. 😄

**Comment by dklima** [comment]
@Ceddix I'm sorry I didn't get your notification of this issue before.

The issue appears to be related with the SQL Statement that was built and tried to use the `data` column.

Have you managed to solve it?

**Comment by Ceddix** [comment]
I found another script, that also stopped working at the `co_sign` table. But with the other script I had the ability to just skip this table.
So there was definitely a problem with the `co_sign` table.

**Comment by dklima** [comment]
I'm glad you figured it out.

**Comment by dklima** [comment]
Hey Ceddix, by any chance you have a sample .db file that have the same error you posted?

I would like to improve the error handling of the script.

Thanks

**Comment by Ceddix** [comment]
I'll see if I still have the database somewhere in the next few days and get back to you! :)

**Comment by dklima** [comment]
This behavior was resolved. Problematic tables will be skipped while migrating.
